# Generated by Django 4.1.7 on 2023-03-29 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_number', models.IntegerField()),
                ('operation', models.CharField(max_length=2)),
                ('second_number', models.IntegerField()),
                ('ans', models.IntegerField()),
            ],
        ),
    ]
